/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoundControlsRouteImport } from './routes/round-controls'
import { Route as PlayerControlsRouteImport } from './routes/player-controls'
import { Route as OverlayRouteImport } from './routes/overlay'
import { Route as IndexRouteImport } from './routes/index'

const RoundControlsRoute = RoundControlsRouteImport.update({
  id: '/round-controls',
  path: '/round-controls',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerControlsRoute = PlayerControlsRouteImport.update({
  id: '/player-controls',
  path: '/player-controls',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayRoute = OverlayRouteImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/overlay': typeof OverlayRoute
  '/player-controls': typeof PlayerControlsRoute
  '/round-controls': typeof RoundControlsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/overlay': typeof OverlayRoute
  '/player-controls': typeof PlayerControlsRoute
  '/round-controls': typeof RoundControlsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/overlay': typeof OverlayRoute
  '/player-controls': typeof PlayerControlsRoute
  '/round-controls': typeof RoundControlsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/overlay' | '/player-controls' | '/round-controls'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/overlay' | '/player-controls' | '/round-controls'
  id: '__root__' | '/' | '/overlay' | '/player-controls' | '/round-controls'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OverlayRoute: typeof OverlayRoute
  PlayerControlsRoute: typeof PlayerControlsRoute
  RoundControlsRoute: typeof RoundControlsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/round-controls': {
      id: '/round-controls'
      path: '/round-controls'
      fullPath: '/round-controls'
      preLoaderRoute: typeof RoundControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player-controls': {
      id: '/player-controls'
      path: '/player-controls'
      fullPath: '/player-controls'
      preLoaderRoute: typeof PlayerControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay': {
      id: '/overlay'
      path: '/overlay'
      fullPath: '/overlay'
      preLoaderRoute: typeof OverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverlayRoute: OverlayRoute,
  PlayerControlsRoute: PlayerControlsRoute,
  RoundControlsRoute: RoundControlsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
